from __future__ import annotations
from .plan import RAG_LORA_USER_PROMPT, RAG_LORA_USER_PROMPT_EN
from .intent_classification import (
    INTENT_FIX_SHOT_USER_PROMPT,
    INTENT_FIX_SHOT_USER_PROMPT_EN,
)
from .tool_selection import (
    TOOL_LIST_SCHEMA,
    TOOL_LIST_SCHEMA_PARAM,
    ONE_SHOT_NAME,
    ONE_SHOT_PARAM,
    RAG_LORA_NAME_USER_PROMPT,
    SELECT_TOOL_EN,
    SELECT_MORE_TOOL_EN,
    SELECT_TOOL_WRONG_EN,
    SELECT_TOOL_HALLUCINATED_EN,
    SELECT_TOOL_WRONG_HALLUCINATED_EN,
)
from .param_filling import (
    RAG_LORA_PARAM_USER_PROMPT,
    FILL_PARAM_EN,
    FILL_MORE_PARAM_EN,
    FILL_PARAM_WRONG_EN,
    FILL_PARAM_FORMAT_WRONG_EN,
)
from .checker import (
    TOOL_CHECKER_SYSTEM_PROMPT,
    TOOL_CHECKER_USER_PROMPT,
    TOOL_CHECKER_SYSTEM_PROMPT_EN,
    TOOL_CHECKER_USER_PROMPT_EN,
)

SYSTEM_PROMPT = "You are a helpful assistant."
